### ISSUE TITLE
Database tables with prefixes cause exception in My Account area

### ISSUE THREAD

**Issue by samcleathero** [Worldpay/Worldpay-Magento2-CG#110] opened 2023-03-27 11:36 UTC
If database tables have a prefix, an exception is thrown when trying to access the My Account area, as shown in the screenshot below.

This is caused by a database join in `Model/ResourceModel/Recurring/Subscription/Collection.php` on line 114 which references the raw table name (`worldpay_recurring_plans`) and does not account for any table prefix which might be configured.

![Database prefix issue screenshot](https://user-images.githubusercontent.com/3945502/227929880-ecb76d5b-b855-4959-8c22-a2da82c9ca45.png)

I will submit a pull request shortly to rectify this.

**Comment by elavarasann** [comment] 2023-05-31 10:54
We have checked in our side but we are not able to reproduce this issue.

**Closed by elavarasann** 2023-05-31 10:54 UTC

**Comment by elavarasann** [comment] 2023-05-31 11:17
Can you send us the version details of our plugin and Magento that you are using. We will re check it again. And did you checked this issue in Vanilla version of Magento ?
